AdoptionMVC/Models/AdoptionDbContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AdoptionMVC.Models;

public partial class AdoptionDbContext : DbContext
{
    public AdoptionDbContext()
    {
    }

    public AdoptionDbContext(DbContextOptions<AdoptionDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Animal> Animals { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.\\sqlexpress;Initial Catalog=AdoptionDb; Integrated Security=SSPI;Encrypt=false;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Animal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Animals__3214EC072396A990");

            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.Breed)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("breed");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Img)
                .HasMaxLength(255)
                .HasColumnName("img");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

AdoptionMVC/Models/Animal.cs
using System;
using System.Collections.Generic;

namespace AdoptionMVC.Models;

public partial class Animal
{
    public int Id { get; set; }

    public string? Img { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Breed { get; set; }

    public int? Age { get; set; }
}

AdoptionMVC/Models/ErrorViewModel.cs
namespace AdoptionMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdoptionMVC/Controllers/AdoptionController.cs
using AdoptionMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdoptionMVC.Controllers
{
    public class AdoptionController : Controller
    {
        AdoptionDbContext dbContext = new AdoptionDbContext();

        [HttpGet]
        public IActionResult Index()
        {
            List<Animal> result = dbContext.Animals.ToList();
            return View(result);
        }

        public IActionResult Breed()
        {
            List<Animal> result=dbContext.Animals.ToList();
            return View(result);
        }

        [HttpGet]
        public IActionResult Result()
        {
            List<Animal> result = dbContext.Animals.ToList();
            return View(result);
        }
        [HttpPost]
        public IActionResult Result(string breed)
        {
            List<Animal> result = dbContext.Animals.Where(b => b.Breed == breed).ToList();
            return View(result);
        }

        public IActionResult Adopt(Animal result)
        {
            return View(result);
        }

        public IActionResult RemoveAnimal(int id)
        {
            Animal Animal = dbContext.Animals.FirstOrDefault(a => a.Id == id);
            dbContext.Animals.Remove(Animal);
            dbContext.SaveChanges();
            return RedirectToAction("Confirmation", new { msg = $"{Animal.Name} has been adopted" });
        }

        public IActionResult AddAnimal(List<Animal> result)
        {
            Animal Animal;
            return View();
        }
        public IActionResult Confirmation(string msg)
        {
            ViewData["msg"] = msg;
            return View();
        }

    }
}

AdoptionMVC/Controllers/HomeController.cs
using AdoptionMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace AdoptionMVC.Controllers
{
    public class HomeController : Controller
    {
        AdoptionDbContext dbContext = new AdoptionDbContext();
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }

        public IActionResult AddAnimal(Animal a)
        {
            dbContext.Animals.Add(a);
            dbContext.SaveChanges();
            return RedirectToAction("Confirmation", new {msg =$"{a.Name} up for adoption"});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Confirmation(string msg)
        {
            ViewData["msg"] = msg;
            return View();
        }
    }
}

AdoptionMVC/Views/Adoption/Adopt.cshtml
@model Animal


<h3>Thank you for your adoption</h3>
<a asp-method="post" asp-action="Index" asp-controller="Home">Return to Home</a>
@{

}

AdoptionMVC/Views/Adoption/Breed.cshtml
@model List<Animal>

    <div>
        <h1>All Available Animals</h1>
    <ul>
    @{
        foreach(Animal a in Model)
        {
            <p>------</p>
            <h3>@a.Name</h3>
            <p><a asp-controller="Adoption" asp-action="RemoveAnimal" asp-route-id="@a.Id">Adopt Me</a></p>
            <img height="500px" src="@a.Img" />

            <p>@a.Description</p>


        }

        }

    </ul>
</div>

AdoptionMVC/Views/Adoption/Index.cshtml
@model List<Animal>

<p>Select a Breed Here.</p>
<form asp-controller="Adoption" asp-action="Result" method="post">
    <select id="Breed" name="Breed">
    @{
        List<string> uniqueCategories = Model.Select(p => p.Breed).Distinct().ToList();
        foreach (string breed in uniqueCategories)
        {
            <option>@breed</option>
        }
        }
    </select>

    <input type="submit" />
</form>
<a asp-method="post" asp-action="Index" asp-controller="Home">Return to Home</a>

AdoptionMVC/Views/Adoption/Result.cshtml
@model List<Animal>

<ul>
    @{
        foreach (Animal a in Model)
        {
            <h1>@a.Name</h1>
            <img height="500px" src="@a.Img" />
            <p>Description: @a.Description</p>
             <a asp-controller="Adoption" asp-action="RemoveAnimal" asp-route-id="@a.Id">Adopt Me</a>
        }

    }

</ul>

AdoptionMVC/Views/Home/Confirmation.cshtml
<h1>@ViewData["msg"]</h1>
<a asp-method="post" asp-action="Index" asp-controller="Home">Return to Home</a>

AdoptionMVC/Views/Home/Form.cshtml
<form asp-action="AddAnimal" asp-method="post">
    <p>Please enter the following information.</p>

    <ul>
        <li>
            <label for="name">Name: </label>
            <input type="text" name="name" id="name" required />

        </li>

        <li>
            <label for="img">Image URL </label>
            <input type="url" name="img" id="img" />

        </li>


        <li>
            <label for="description">Description </label>
            <input type="text" name="description" id="description" />

        </li>


        <li>
            <label for="breed">Breed </label>
            <input type="text" name="breed" id="breed" />

        </li>
        <label for="age">Age </label>
        <input type="number" name="age" id="age" />

        </li>

        <input type="reset" />

        <input type="submit" />
    </ul>
</form>

AdoptionMVC/Views/Home/Index.cshtml
@model List<Animal>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Pet Adoption Center</h1>
<p> See all Animals <a asp-controller="Adoption" asp-action="Breed">Here</a></p>
    <p> To Select an animal by Breed click <a asp-controller="Adoption" asp-action="Index">Here</a></p>
<p>Add Animal to Adoption List <a asp-controller="Home" asp-action="Form">Here</a></p>
</div>

AdoptionMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdoptionMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdoptionMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdoptionMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Adoption" asp-action="Index">Adoption</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdoptionMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>